In [0]:
import gym
import numpy as np 

In [0]:
# 1. Load Environment and Q-table structure
#is_slippery = False - this is the deterministic situation
#if you remove it, you get the slippery 
env = gym.make("FrozenLake-v0", is_slippery=False) #change to true
#env = gym.make("FrozenLake8x8-v0", is_slippery=False) #change size of the pond 
Q = np.zeros([env.observation_space.n,env.action_space.n])
# env.obeservation.n, env.action_space.n gives number of states and action in env loaded
# 2. Parameters of Q-leanring
eta = .628
gma = .9
episode = 10000
rev_list = [] # rewards per episode calculate

In [4]:
# 3. Q-learning Algorithm
for i in range(episode):
    # Reset environment
    print("New episode")
    print("state action")
    
    s = env.reset()
    info = env.step(env.action_space.sample())
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        #env.render()
        j+=1
        # Choose action from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state & reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + eta*(r + gma*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        print("%i %i" %(s,a))
        print("reward = %f" %r)
        print(info)
        #print(s1)
        if d == True:
            break
    print("number of steps = %i" %j)
    rev_list.append(rAll)
    #env.render()



Streaming output truncated to the last 5000 lines.
number of steps = 16
New episode
state action
9 2
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
10 2
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
11 2
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
12 2
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
13 2
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
5 3
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
6 2
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
7 2
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
15 1
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
23 1
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
31 1
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
39 1
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
47 1
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
55 1
reward = 0.000000
(8, 0.0, False, {'prob': 1.0})
63 1
reward = 1.000000
(8, 0.0, False, {'prob': 1.0})
number of steps = 15
New episode
state action
9 2
reward = 0.000000
(8, 0.0, False, {'prob': 1.0}

In [5]:
print ("Reward Sum on all episodes %f"  %(sum(rev_list)/episode))
print ("Final Values Q-Table")
print (Q)

Reward Sum on all episodes 0.833000
Final Values Q-Table
[[1.11319912e-04 5.28141578e-05 2.25607741e-01 1.84587795e-04]
 [0.00000000e+00 0.00000000e+00 2.28767925e-01 3.05007253e-04]
 [0.00000000e+00 0.00000000e+00 2.54186583e-01 0.00000000e+00]
 [2.13201270e-04 0.00000000e+00 2.82429536e-01 0.00000000e+00]
 [0.00000000e+00 3.13810596e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.30467210e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.78296900e-01 0.00000000e+00]
 [0.00000000e+00 5.31441000e-01 0.00000000e+00 0.00000000e+00]
 [3.84942841e-05 0.00000000e+00 3.06762232e-03 0.00000000e+00]
 [3.84942841e-05 0.00000000e+00 2.54186583e-01 1.20501358e-04]
 [0.00000000e+00 0.00000000e+00 2.82429536e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.13810596e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.48678440e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.87420489e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00

In [6]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(99):
        env.render()
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(Q[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            break
        state = new_state
env.close()

****************************************************
EPISODE  0

SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Down)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Down)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
  (Down)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFF